# install sensu
- name: add repo
  shell: wget -q http://repos.sensuapp.org/apt/pubkey.gpg -O- | sudo apt-key add -
- name: install sensu
  yum: name=sensu state=installed
- name: add cert
  copy: src=files/sensu/ssl/{{ item }} dest=/etc/sensu/ssl/{{ item }} owner=root group=root
  with_items:
    - key.pem
    - cert.pem

- name: configure rabbitmq
  template: src=templates/sensu/conf.d/rabbitmq.json dest=/etc/sensu/rabbitmq.json

- include: client.yml
  when: sensu_install_client == true
